# Display a random pearl of Sterling Archer Wisdom
#
# hubot archer - returns a random Sterling Archer Quote
archisms = [
  "My tongue says sangria by my heart says michelada."
  "I left my lightsaber in my other space pants."
  "I dunno, maybe a mutiny of clowns."
  "Bloody mary, blessed are you among cocktails. Pray for me now in the hour of my death, which I hope is soon. Amen."
  "I bet i wont even be able to eat spaghetti and meatballs ever again. Oh god, I could eat. Not necessarily spaghetti and meatballs, but not necessarily not spaghetti and meatballs. I mean I really like spaghetti and meatballs. Man, if I don't get some spaghetti and meatballs I might literally die."
  "They called you exotic. Which is just people talk for awesome. Which you are."
  "I got to blow up a train."
  "Thanks, Freddy Foreshadowing."
  "Speaking of excellence, did you hear we met a tiger? Then he got murdered."
  "I gotta get back to Earth before the Stargate closes."
  "New hot tub. 50 jets. Hand hewned California Redwood. No big deal."
  "It's pretty hard to stay anonymous when you're the world's greatest secret agent."
  "I'm sorry I can't hear you over the sound of my giant throbbing erection."
  "Noah, I'm half drunk and slathered in every bodily fluid there is... so yeah... this is about as Pirate Kingy as I'm going to get so brief away... Noah... Good Morning."
  "If I stop drinking all at once, I'm afraid the cumulative hangover will kill me."
  "Does Canada even have a spy agency?"
  "Do you like to travel? Because if you don't find that bag, I will empty the entire contents of your body and use your leathery skin as a replacement."
  "How is this happy play time? Use your imaginations, make a soccer ball out of a dead cat."
  "Those cannot be your only shoes. What am I saying? It's Russia. People probably come from miles around just to get their picture taken in those."
  "I thought they just wanted my hair so their scientists could unlock the secret of its luxurious fullness. Touch it, Barry."
  "Didja, wanna shut your negative bad wordsy mouth!?"
  "Lana, lana, lana, lana, LANNNNNAAAAAAA!! Danger Zone...."
  "Not that. Woodhouse, he's all tied up somewhere. Scared and alone. Ha ha ha, probably dehydrated."
  "Um, phrasing."
  "You know what's dangerous? You're obsession with me. Seriously, Lana, call Kenny Loggins, 'cause you're in the Danger Zone."
  "Duh! You think I'm an idiot? I know he wants to marry mother and have her cut me out of the will. Which is why I'm going to kill him."
  "Karate: the Dane Cook of martial arts? No. ISIS agents use Krav Maga. We got an ex-Mossad guy who comes in on Thursdays."
  "Hey com 'on, you know I'd never let anything happen to your bacon. I love you Santa Clause. I do."
  "I am drunk, or I wouldn't be talking to you."
  "Lying is like 95% of what I do."
  "Stop. Shut up. I have to go, and If I find one single dog hair when I get back, I'll... rub sand in your dead little eyes."
  "Aw, com 'on. At worst that was 'needs improvement.'"
  "What, your little go-kart battery?"
  "It's like my brain's a tree and you're those little cookie elves."
  "Sorry, my lemur ran across my keyboard."
  "Why are those noisy neighbors always stomping above you? Honestly, I wouldn't know. I live in a penthouse."
  "Waiting (eagerly) for bowler hats to come back in style."
  "The Brandy Alexander was created to celebrate the victory over the Persians. Who I think are now Iranians. But also, who cares?"
  "Some say war is not the answer. Maybe they're right… unless… 'How can I conquer that country?' is the question."
  "In Iceland, 1/3 of the population doesn't show up to work on the average day. I assume they're busy knocking themselves unconscious with rocks."
  "AJTTOTD: Make sure to mail that thing you've been meaning to mail lately."
  "AJTTOTD: It's always impressive if you play an instrument, but it's even more impressive to tell people you 'dabble on the sax'."
  "Norwegians drink 15 times more coffee than the average Irish person. I drink enough alcohol, daily, to kill Ireland. So there. We all win."
  "'New York City traffic isn't that bad,' said no one, ever."
  "AJTTOTD: If you can't fall asleep, don't listen to a machine that makes fake ocean noises… Buy a house on the beach. Way better."
  "AJTTOTD: Never hesitate to give your enemy a Road House kick to the face."
  "AJTTOTD: Don't push your luck in places you've already been banned. Twice."
  "AJTTOTD: You should only wear a string tie if you invented fried chicken."
]

module.exports = (robot) ->
  robot.respond /archer(\s+ me)?/i, (msg) ->
    msg.send msg.random archisms
