# Description:
#   Return a specified eponymous law
#
# Dependencies:
#   None
#
# Configuration:
#   None
#
# Commands:
#   hubot law <name> - Returns <name>'s law
#
# Author:
#   A. Gianotto - @snipe

laws = 
  "aitken": "Aitken's law - Describes how vowel length in Scots and Scottish English is conditioned by environment. Named for Professor A. J. Aitken, who formulated it."
  "allen": "Allen's rule - Endotherms from colder climates usually have shorter limbs (or appendages) than the equivalent animals from warmer climates."
  "amagat": "Amagat's law - Describes the behaviour and properties of mixtures of ideal gases. Named for Émile Amagat."
  "amara": "Amara's law - \"We tend to overestimate the effect of a technology in the short run and underestimate the effect in the long run.\""
  "amdahl": "Amdahl's law - Used to find out the maximum expected improvement to an overall system when only a part of it is improved. Named after Gene Amdahl (born 1922)."
  "ampère": "Ampère's circuital law - In physics, it relates the circulating magnetic field in a closed loop to the electric current passing through the loop. Discovered by André-Marie Ampère."
  "anderson": "Anderson's rule - Used for the construction of energy band diagrams of the heterojunction between two semiconductor materials. Named for R. L. Anderson."
  "archie": "Archie's law - In petrophysics, relates the in-situ electrical conductivity of sedimentary rock to its porosity and brine saturation. Named for Gus Archie (1907-1978)."
  "archimedes": "Archimedes' principle - Indicates that the upward buoyant force that is exerted on a body immersed in a fluid, whether fully or partially submerged, is equal to the weight of the fluid that the body displaces. Named for Archimedes."
  "atwood": "Atwood's Law - Any software that can be written in JavaScript will eventually be written in JavaScript."
  "augustine": "Augustine's laws - on air force management. Named for Norman Augustine."
  "avogadro": "Avogadro's law - In chemistry and physics, one of the gas laws, relating to the volume and molarity of a gas."
  "babinet": "Babinet's principle - In physics, states that the diffraction pattern from an opaque body is identical to that from a hole of the same size and shape except for the overall forward beam intensity. Named for Jacques Babinet."
  "barlow": "Barlow's law - was an incorrect physical law proposed by Peter Barlow in 1825 to describe the ability of wires to conduct electricity."
  "baumol": "Baumol's cost disease - In inflation, effect of productivity growth in one sector forcing salary increases in all sectors leading to the other more labor-intensive sectors having prices rise faster than the general rate of inflation (e.g. government, music, healthcare, education)."
  "bayes": "Bayes' theorem - In probability theory, shows the relation between one conditional probability and its inverse."
  "bechdel": "Bechdel test - test for gender bias, asks whether a work of fiction features at least two women who talk to each other about something other than a man."
  "beckstrom": "Beckstrom's law - In economics, states that the value of a network equals the net value added to each user’s transactions conducted through that network, summed over all users. Named for Rod Beckstrom."
  "beer-lambert": "Beer-Lambert law - In optics, the empirical relationship of the absorption of light to the properties of the material through which the light is traveling. Independently discovered (in various forms) by Pierre Bouguer in 1729, Johann Heinrich Lambert in 1760 and August Beer in 1852."
  "bell": "Bell's theorem - No physical theory of local hidden variables can ever reproduce all of the predictions of quantum mechanics. Named for John Stewart Bell."
  "benford": "Benford's law - In any collection of statistics, a given statistic has roughly a 30% chance of starting with the digit 1."
  "bennett": "Bennett's laws - A concept in quantum information theory. Named for Charles H. Bennett."
  "bergmann": "Bergmann's rule - within a broadly distributed taxonomic clade, populations and species of larger size are found in colder environments, and species of smaller size are found in warmer regions."
  "bernoulli": "Bernoulli's principle - In fluid dynamics, describes the effect that flow has on pressure contributing lift to airfoils."
  "betteridge": "Betteridge's law of headlines - In journalism, \"any headline which ends in a question mark can be answered by the word 'no'\"."
  "biot-savart": "Biot-Savart law - Describes the magnetic field set up by a steady current density. Named for Jean-Baptiste Biot and Félix Savart."
  "birch": "Birch's law - In geophysics, establishes a linear relation of the compressional wave velocity of rocks and minerals of a constant average atomic weight. Named after Francis Birch."
  "born": "Born's law - In quantum mechanics, gives the probability that a measurement on a quantum system will yield a given result. Named after physicist Max Born."
  "boyle": "Boyle's law - In physics, one of the gas laws, relating the volume and pressure of an ideal gas held at a constant temperature. Discovered by and named after Robert Boyle (1627-1691)."
  "bradford": "Bradford's law - a pattern described by Samuel C. Bradford in 1934 that estimates the exponentially diminishing returns of extending a library search."
  "bragg": "Bragg's law - In physics, gives the angles for coherent and incoherent scattering from a crystal lattice."
  "bremermann": "Bremermann's limit - Named after Hans-Joachim Bremermann, is the maximum computational speed of a self-contained system in the material universe."
  "briffault": "Briffault's Law - \"The female, not the male, determines all the conditions of the animal family. Where the female can derive no benefit from association with the male, no such association takes place.\" Named after Robert Briffault."
  "brooks": "Brooks' law - \"Adding manpower to a late software project makes it later.\" Named after Fred Brooks, author of the well known book on project management The Mythical Man-Month."
  "buysballot": "Buys Ballot's law - Concerned with the notion that the wind travels counterclockwise around low pressure zones in the Northern Hemisphere. Named for C. H. D. Buys Ballot, who published an empirical validation of an existing theory, in 1857."
  "byerlee": "Byerlee's law - Gives the stress circumstances in the Earth's crust at which fracturing along a geological fault takes place."
  "campbell": "Campbell's law - \"The more any quantitative social indicator is used for social decision making, the more subject it will be to corruption pressures and the more apt it will be to distort and corrupt the social processes it is intended to monitor.\"[1] Named after Donald T. Campbell (1916-1996)"
  "cassie": "Cassie's law - Describes the effective contact angle θc for a liquid on a composite surface."
  "cassini": "Cassini's laws - provide a compact description of the motion of the Moon. Established in 1693 by Giovanni Domenico Cassini."
  "celine": "Celine's laws - Celine's laws are a series of three laws regarding government and social interaction attributed to the fictional character Hagbard Celine from Robert Anton Wilson's The Illuminatus! Trilogy."
  "charles": "Charles's law - States that at constant pressure, the volume of a given mass of a gas increases or decreases by the same factor as its temperature (in kelvins) increases or decreases. Named after Jacques Charles."
  "child": "Child's law - States that the space-charge limited current in a plane-parallel diode varies directly as the three-halves power of the anode voltage and inversely as the square of the distance separating the cathode and the anode. Named after Clement D. Child; also known as the Child-Langmuir Law (after Irving Langmuir). See also Mott-Gurney law."
  "chladni": "Chladni's law - Relates the frequency of modes of vibration for flat circular surfaces with fixed center as a function of the numbers of diametric (linear) nodes and of radial (circular) nodes. Named after Ernst Chladni."
  "claasen": "Claasen's law - Theo Claasen's \"logarithmic law of usefulness\" - 'usefulness = log(technology)'."
  "clarke": "Clarke's three laws - Formulated by Arthur C. Clarke. Several corollaries to these laws have also been proposed.\nFirst law: When a distinguished but elderly scientist states that something is possible, he is almost certainly right. When he states that something is impossible, he is very probably wrong.\nSecond law: The only way of discovering the limits of the possible is to venture a little way past them into the impossible.\nThird law: Any sufficiently advanced technology is indistinguishable from magic."
  "conway": "Conway's law - Any piece of software reflects the organizational structure that produced it. Named after Melvin Conway."
  "cooper": "Cooper's law - The number of radio frequency conversations which can be concurrently conducted in a given area doubles every 30 months."
  "cope": "Cope's rule - Population lineages tend to increase in body size over evolutionary time."
  "coulomb": "Coulomb's law - An inverse-square law indicating the magnitude and direction of electrostatic force that one stationary, electrically charged object of small dimensions (ideally, a point source) exerts on another. It is named after Charles-Augustin de Coulomb."
  "cunningham": "Cunningham's law - The best way to get the right answer on the Internet is not to ask a question, it’s to post the wrong answer. Attributed to Ward Cunningham by Steven McGeady."
  "curie": "Curie's law - In a paramagnetic material the magnetization of the material is (approximately) directly proportional to an applied magnetic field. Named after Pierre Curie."
  "dalembert": "D'Alembert's principle - States that the sum of the differences between the forces acting on a system of mass particles and the time derivatives of the momenta of the system itself along any virtual displacement consistent with the constraints of the system, is zero. Named after Jean le Rond d'Alembert."
  "dale": "Dale's principle - In neuroscience, states that a neuron is capable of producing and secreting only one neurotransmitter from its axon terminals. Named after Henry Hallett Dale but more recent data suggests it to be false. A more common interpretation of the original statement made by Dale is that neurons release the same set of transmitters at all of their synapses."
  "dalton": "Dalton's law - In chemistry and physics, states that the total pressure exerted by a gaseous mixture is equal to the sum of the partial pressures of each individual component in a gas mixture. Also called Dalton's law of partial pressure, and related to the ideal gas laws, this empirical law was observed by John Dalton in 1801."
  "darcy": "Darcy's law - In hydrogeology, describes the flow of a fluid (such as water) through a porous medium (such as an aquifer)."
  "davis": "Davis' law - In anatomy, describes how soft tissue models along imposed demands. Corollary to Wolff's law."
  "demorgan": "De Morgan's laws - Apply to formal logic regarding the negation of pairs of logical operators."
  "denard-scaling": "Denard scaling - States that the computing performance per watt grows exponentially at roughly the same rate as Moore's law."
  "dermott": "Dermott's law - The sidereal period of major satellites tends to follow a geometric series. Named after Stanley Dermott."
  "dilbert": "Dilbert principle - Coined by Scott Adams as a variation of the Peter Principle of employee advancement. Named after Adams' Dilbert comic strip, it proposes that \"the most ineffective workers are systematically moved to the place where they can do the least damage: management.\""
  "doctorow": "Doctorow's Law - \"Anytime someone puts a lock on something you own, against your wishes, and doesn't give you the key, they're not doing it for your benefit.\""
  "dolbear": "Dolbear's law - an empirical relationship between temperature and the rate of cricket chirping."
  "dollo": "Dollo's law - \"An organism is unable to return, even partially, to a previous stage already realized in the ranks of its ancestors.\" Simply put this law states that evolution is not reversible."
  "dulong-petit": "Dulong-Petit law - States the classical expression for the specific heat capacity of a crystal due to its lattice vibrations. Named for Pierre Louis Dulong and Alexis Thérèse Petit."
  "dunbar": "Dunbar's number - A theoretical cognitive limit to the number of people with whom one can maintain stable social relationships. No precise value has been proposed for Dunbar's number, but a commonly cited approximation is 150. First proposed by British anthropologist Robin Dunbar."
  "dunning-kruger": "Dunning-Kruger effect - Is a cognitive bias in which unskilled individuals suffer from illusory superiority, mistakenly rating their ability much higher than average. This bias is attributed to a metacognitive inability of the unskilled to recognize their mistakes."
  "duverger": "Duverger's law - After Maurice Duverger. Winner-take-all (or first-past-the-post) electoral systems tend to create a 2 party system, while proportional representation tends to create a multiple party system."
  "einasto": "Einasto's law - Relates the density of a galaxy to distance from the center. Named for Jaan Einasto."
  "emmert": "Emmert's law - In optics, objects that generate retinal images of the same size will look different in physical size (linear size) if they appear to be located at different distances. Named for Emil Emmert."
  "faraday": "Faraday's law of induction - States that a magnetic field changing in time creates a proportional electromotive force. Named for Michael Faraday, based on his work in 1831."
  "faraday": "Faraday's law of electrolysis - States that the mass of a substance produced at an electrode during electrolysis is proportional to the number of moles of electrons transferred at that electrode; again named for Michael Faraday."
  "fick": "Fick's laws of diffusion - Describe diffusion, and define the diffusion coefficient D. Derived by Adolf Fick in the year 1855."
  "finagle": "Finagle's law - Related to Murphy's Law, states \"Anything that can go wrong, will - at the worst possible time.\""
  "fitts": "Fitts' law - A principle of human movement published in 1954 by Paul Fitts which predicts the time required to move from a starting position to a final target area. Fitts' law is used to model the act of pointing, both in the real world, e.g. with a hand or finger, and on a computer, e.g. with a mouse."
  "fourier": "Fourier's law, also known as the law of heat conduction, states that the time rate of heat flow Q through a slab (or a portion of a perfectly insulated wire) is proportional to the gradient of temperature difference; named for Joseph Fourier."
  "gall": "Gall's law - \"A complex system that works is invariably found to have evolved from a simple system that worked.\""
  "gause": "Gause's law - In ecology, the competitive exclusion principle: \"complete competitors cannot coexist.\""
  "gauss": "Gauss's law - In physics, gives the relation between the electric flux flowing out a closed surface and the charge enclosed in the surface. It was formulated by Carl Friedrich Gauss. See also Gauss' law for gravity, and Gauss's law for magnetism."
  "gay-lussac": "Gay-Lussac's law - \"The pressure of a fixed mass and fixed volume of a gas is directly proportional to the gas's temperature.\""
  "gibrat": "Gibrat's law —\"The size of a firm and its growth rate are independent.\""
  "ginsberg": "Ginsberg's theorem - A set of adages based on the laws of thermodynamics."
  "godwin": "Godwin's law - An adage in Internet culture that states, \"As an online discussion grows longer, the probability of a comparison involving Nazis or Hitler approaches one.\" Coined by Mike Godwin in 1990. (There are many variants drawing from Godwin's Law; Earle's Law, for example, states that as any discussion of online/virtual game economies progresses, the likelihood of EVE Online being mentioned approaches 100%. Another variant states that the more times Deus Ex is mentioned in a discussion, the probability of at least one person (re-)installing it approaches 100%.)"
  "gompertz-makeham": "Gompertz-Makeham law of mortality - States that the death rate is the sum of an age-independent component and an age-dependent component."
  "goodhart": "Goodhart's law - When a measure becomes a target, it ceases to be a good measure."
  "gossen": "Gossen's laws - Three laws in economics relating to utility and value formulated by Hermann Heinrich Gossen."
  "graham": "Graham's law - In physics, a gas law which states that the average kinetic energy of the molecules of two samples of different gases at the same temperature is identical. It is named for Thomas Graham (1805-1869), who formulated it."
  "greenspun": "Greenspun's tenth rule - Any sufficiently complicated C or Fortran program contains an ad hoc, informally specified, bug-ridden, slow implementation of half of Common Lisp; coined by Philip Greenspun."
  "gresham": "Gresham's law - Typically stated as \"Bad money drives good money out of circulation\", but more accurately \"Bad money drives good money out of circulation if their exchange rate is set by law.\" Coined in 1858 by British economist Henry Dunning Macleod, and named for Sir Thomas Gresham (1519-1579). The principle had been stated before Gresham by others, including Nicolaus Copernicus."
  "grimm": "Grimm's law - Explains correspondence between some consonants in Germanic languages and those in other Indo-European languages. Discovered by Jacob Grimm, (1785-1863), German philologist and mythologist and one of the Brothers Grimm."
  "grosch": "Grosch's law - Herb Grosch in 1965 argued that the economic value of computation increases with the square root of the increase in speed—that is, to do a calculation 10 times as cheaply you must do it 100 times as fast."
  "grotthuss-draper": "Grotthuss-Draper law - states that only that light which is absorbed by a system can bring about a photochemical change. Named for Theodor Grotthuss and John William Draper."
  "gustafson": "Gustafson's law (also known as Gustafson-Barsis' law) - a law in computer engineering, that any sufficiently large problem can be efficiently parallelized. Coined by John Gustafson in 1988."
  "haber": "Haber's rule - A mathematical statement relating the concentration of a poisonous gas and how long it must be breathed to result in death."
  "haitz": "Haitz's law - an observation and forecast about the steady improvement, over many years, of light-emitting diodes (LEDs)."
  "hamilton": "Hamilton's principle - States that the dynamics of a physical system is determined by a variational problem for a functional based on a single function, the Lagrangian, which contains all physical information concerning the system and the forces acting on it. Named after William Rowan Hamilton."
  "hanlon": "Hanlon's razor - A corollary of Finagle's law, and a play on Occam's razor, normally taking the form, \"Never attribute to malice that which can be adequately explained by stupidity.\" As with Finagle, possibly not strictly eponymous. Alternatively, \"Do not invoke conspiracy as explanation when ignorance and incompetence will suffice, as conspiracy implies intelligence.\""
  "hartley": "Hartley's law - A way to quantify information and its line rate in an analog communications channel. Named for Ralph Hartley (1888-1970)."
  "hauser": "Hauser's law - Empirical observation about U.S. tax receipts as a percentage of GDP, theorized to be a natural equilibrium."
  "hawthorne": "Hawthorne effect - A form of reactivity whereby subjects improve an aspect of their behavior being experimentally measured simply in response to the fact that they are being studied. Named after Hawthorne Works."
  "hebb": "Hebb's law - \"Neurons that fire together wire together.\""
  "heisenberg": "Heisenberg's Uncertainty principle - States that one cannot measure values (with arbitrary precision) of certain conjugate quantities, which are pairs of observables of a single elementary particle. The most familiar of these pairs is position and momentum."
  "henry": "Henry's law - The mass of a gas that dissolves in a definite volume of liquid is directly proportional to the pressure of the gas provided the gas does not react with the solvent."
  "herblock": "Herblock's law - \"If it's good, they'll stop making it.\" Possibly coined by Herbert Lawrence Block, whose pen name was Herblock."
  "hess": "Hess's law - In physical chemistry, the total enthalpy change during the complete course of a reaction is the same whether the reaction is made in one step or in several steps."
  "hick": "Hick's law - In psychology, the time it takes for a person to make a decision as a function of the number of possible choices."
  "hofstadter": "Hofstadter's law - \"It always takes longer than you expect, even when you take into account Hofstadter's Law\" (Douglas Hofstadter, Gödel, Escher, Bach, 1979)."
  "hooke": "Hooke's law - The tension on a spring or other elastic object is proportional to the displacement from the equilibrium. Frequently cited in Latin as \"Ut tensio sic vis.\" Named after Robert Hooke (1635-1703)."
  "hotelling": "Hotelling's law in economics - Under some conditions, it is rational for competitors to make their products as nearly identical as possible."
  "hubble": "Hubble's law - Galaxies recede from an observer at a rate proportional to their distance to that observer. Formulated by Edwin Hubble in 1929."
  "hume": "Hume's law - In meta-ethics, the assertion that normative statements cannot be deduced exclusively from descriptive statements."
  "humphrey": "Humphrey's law - conscious attention to a task normally performed automatically can impair its performance. Described by psychologist George Humphrey in 1923."
  "hund": "Hund's rules - Three rules in atomic physics used to determine the term symbol that corresponds to the ground state of a multi-electron atom. Named after Friedrich Hund."
  "hutber": "Hutber's law - \"Improvement means deterioration.\" Coined by financial journalist Patrick Hutber."
  "isaac Bonewits": "Isaac Bonewits's laws of magic - \"Laws\" synthesized from a multitude of belief systems from around the world, collected in order to explain and categorize magical beliefs within a cohesive framework."
  "jevons": "Jevons paradox - The proposition that technological progress that increases the efficiency with which a resource is used tends to increase (rather than decrease) the rate of consumption of that resource."
  "joule": "Joule's laws - Heat laws related to electricity and to gasses, named for James Prescott Joule."
  "kepler": "Kepler's laws of planetary motion - Describe the motion of the planets around the sun. First articulated by Johannes Kepler."
  "kerckhoffs": "Kerckhoffs' principle of secure cryptography - A cryptosystem should be secure even if everything about the system, except the key, is public."
  "kirchhoff": "Kirchhoff's laws - One law in thermodynamics and two about electrical circuits, named after Gustav Kirchhoff."
  "klaiber": "Klaiber's law - That the silicon wafer size will dictate the largest diameter of ultrapure water supply piping needed within a semiconductor wafer factory."
  "koomey": "Koomey's law - That the energy of computation is halved every year and a half."
  "kopp": "Kopp's law - The molecular heat capacity of a solid compound is the sum of the atomic heat capacities of the elements composing it. Named for Hermann Franz Moritz Kopp."
  "korte": "Korte's law - The greater the length of a path between two successively presented stimuli, the greater the stimulus onset asynchrony must be for an observer to perceive the two stimuli as a single moving object."
  "kranzberg": "Kranzberg's first law of technology - Technology is neither good nor bad; nor is it neutral.[2]"
  "lhopital": "L'Hôpital's rule - This rule uses derivatives to find limits of indeterminate forms 0/0 or ±∞/∞, and only applies to such cases."
  "lanchester": "Lanchester's laws - formulae for calculating the relative strengths of predator/prey pair and application in military conflict."
  "landauer": "Landauer's principle - Asserts that there is a minimum possible amount of energy required to change one bit of information, known as the Landauer limit."
  "leibniz": "Leibniz's law - A principle in metaphysics also known as the Identity of Indiscernibles. It states: \"If two objects have all their properties in common, then they are one and the same object.\""
  "lenz": "Lenz's law - An induced current is always in such a direction as to oppose the motion or change causing it."
  "lewis": "Lewis's law - The comments on any article about feminism justify feminism."
  "liebig": "Liebig's law of the minimum - The growth or distribution of a plant is dependent on the one environmental factor most critically in demand."
  "linus": "Linus' law - \"Given enough eyeballs, all bugs are shallow.\" Named for Linus Torvalds."
  "little": "Little's law - In queuing theory, \"The average number of customers in a stable system (over some time interval) is equal to their average arrival rate, multiplied by their average time in the system.\" The law was named for John Little from results of experiments in 1961."
  "littlewood": "Littlewood's law - States that individuals can expect miracles to happen to them, at the rate of about one per month. Coined by Professor J E Littlewood, (1885-1977)."
  "lotka": "Lotka's law - In infometrics, states that the number of authors publishing a certain number of articles is a fixed ratio to the number of authors publishing a single article. As the number of articles published increases, authors producing that many publications become less frequent. For example, there may be 1/4 as many authors publishing two articles within a specified time period as there are single-publication authors, 1/9 as many publishing three articles, 1/16 as many publishing four articles, etc. Though the law itself covers many disciplines, the actual ratios involved are very discipline-specific."
  "malthusian": "Malthusian growth model - Also referred to as the Malthusian law or simple exponential growth model, is exponential growth based on a constant rate. The model is named after Thomas Robert Malthus, who wrote An Essay on the Principle of Population (1798), one of the earliest and most influential books on population."
  "marconi": "Marconi's law - An empirical law that relates radio communication distance to antenna tower height"
  "meadow": "Meadow's law - A precept, now discredited, that since cot deaths are so rare, \"One is a tragedy, two is suspicious and three is murder, until proved otherwise.\" It was named for Sir Roy Meadow, a discredited paediatrician prominent in the United Kingdom in the last quarter of the twentieth century."
  "mendel": "Mendel's laws - Named for the 19th century Austrian monk Gregor Mendel who determined the patterns of inheritance through his plant breeding experiments, working especially with peas. Mendel's first law, or the law of segregation, states that each organism has a pair of genes; that that it inherits one from each parent, and that the organism will pass down only one of these genes to its own offspring. These different copies of the same gene are called alleles. Mendel's second law, the law of independent assortment, states that different traits will be inherited independently by the offspring."
  "menzerath": "Menzerath's law, or Menzerath-Altmann law (named after Paul Menzerath and Gabriel Altmann), is a linguistic law according to which the increase of a linguistic construct results in a decrease of its constituents, and vice versa."
  "metcalfe": "Metcalfe's law - In communications and network theory, states that the value of a system grows as approximately the square of the number of users of the system. Framed by Robert Metcalfe in the context of ethernet."
  "miller": "Miller's law - In communication, states: \"To understand what another person is saying, you must assume that it is true and try to imagine what it could be true of.\" Named after George Armitage Miller. In psychology, states that the number of objects an average person can hold in working memory is about seven. Also named after George Miller. In software development, states: \"All discussions of incremental updates to Bugzilla will eventually trend towards proposals for large scale redesigns or feature additions or replacements for Bugzilla.\" Named after Dave Miller."
  "miller-rule": "Miller's Rule - In optics, an empirical rule which gives an estimate of the order of magnitude of the nonlinear coefﬁcient."
  "mooers": "Mooers' law - \"An information retrieval system will tend not to be used whenever it is more painful and troublesome for a customer to have information than for him not to have it.\" An empirical observation made by American computer scientist Calvin Mooers in 1959."
  "moore": "Moore's law - An empirical observation stating that the complexity of integrated circuits doubles every 24 months. Outlined in 1965 by Gordon Moore, co-founder of Intel."
  "moravec": "Moravec's paradox - \"it is comparatively easy to make computers exhibit adult level performance on intelligence tests or playing checkers, and difficult or impossible to give them the skills of a one-year-old when it comes to perception and mobility.\""
  "muphry": "Muphry's law - \"If you write anything criticizing editing or proofreading, there will be a fault of some kind in what you have written.\" The editorial equivalent of Murphy's law, according to John Bangsund."
  "murphy": "Murphy's law - \"Anything that can go wrong will go wrong.\" Ascribed to Edward A. Murphy, Jr."
  "maismith": "Naismith's rule - A rule of thumb that helps in the planning of a walking or hiking expedition by calculating how long it will take to walk the route, including ascents."
  "neuhaus": "Neuhaus's law - Where orthodoxy is optional, orthodoxy will sooner or later be proscribed. This \"law\" had been expressed earlier. For example, Charles Porterfield Krauth wrote in his The Conservative Reformation: \"Truth started with tolerating; it comes to be merely tolerated, and that only for a time. Error claims a preference for its judgments on all disputed points.\""
  "newton-cooling": "Newton's law of cooling - The rate of cooling (or heating) of a body due to convection is proportional to the difference between the body temperature and the ambient temperature."
  "newton-motion": "Newton's laws of motion - In physics, three scientific laws concerning the behaviour of moving bodies, which are fundamental to classical mechanics (and since Einstein, which are valid only within inertial reference frames). Discovered and stated by Isaac Newton (1643-1727), they can be formulated, in modern terms, as follows:\n\nFirst law: \"A body remains at rest, or keeps moving in a straight line (at a constant velocity), unless acted upon by a net outside force.\"\nSecond law: \"The acceleration of an object of constant mass is proportional to the net force acting upon it.\"\nThird law: \"Whenever one body exerts a force upon a second body, the second body exerts an equal and opposite force upon the first body.\""
  "niven": "Niven's laws: \"If the universe of discourse permits the possibility of time travel and of changing the past, then no time machine will be invented in that universe.\""
  "nyquist": "Nyquist rate - The minimum sampling rate required to avoid aliasing is equal to twice the highest frequency contained within the signal. Named after Harry Nyquist."
  "occam": "Occam's razor - States that explanations should never multiply causes without necessity. (\"Entia non sunt multiplicanda praeter necessitatem.\") When two or more explanations are offered for a phenomenon, the simplest full explanation is preferable. Named after William of Ockham (ca.1285-1349)."
  "ohm": "Ohm's law - In physics, states that the ratio of the potential difference (or voltage drop) between the ends of a conductor (and resistor) to the current flowing through it is a constant. Discovered by and named after Georg Simon Ohm (1789-1854)."
  "ohm": "Ohm's acoustic law - An empirical approximation concerning the perception of musical tones, named for Georg Simon Ohm."
  "okrent": "Okrent's law - Daniel Okrent's take on the argument to moderation."
  "okun": "Okun's law - In economics, this refers to the trend that every time unemployment increases by 1%, a 2% decrease in the annual GDP occurs."
  "orgel": "Orgel's rules - In evolutionary biology, a set of axioms attributed to the evolutionary biologist Leslie Orgel.\nFirst rule: \"Whenever a spontaneous process is too slow or too inefficient a protein will evolve to speed it up or make it more efficient.\"\nSecond rule: \"Evolution is cleverer than you are.\""
  "pareto-optimality": "Pareto optimality - Given an initial allocation of goods among a set of individuals, a change to a different allocation that makes at least one individual better off without making any other individual worse off is called a Pareto improvement. An allocation is defined as \"Pareto efficient\" or \"Pareto optimal\" when no further Pareto improvements can be made."
  "pareto-principle": "Pareto principle - States that for many phenomena 80% of consequences stem from 20% of the causes. Named after Italian economist Vilfredo Pareto, but framed by management thinker Joseph M. Juran."
  "parkinson": "Parkinson's law - \"Work expands to fill the time available for its completion.\" Corollary: \"Expenditure rises to meet income.\" Coined by C. Northcote Parkinson (1909-1993)."
  "parkinson-triviality": "Parkinson's law of triviality - \"The time spent on any agenda item will be in inverse proportion to the sum of money involved.\" Also due to C. Northcote Parkinson."
  "peter": "Peter principle - \"In a hierarchy, every employee tends to rise to his level of incompetence.\" Coined by Dr. Laurence J. Peter (1919-1990) in his book The Peter Principle. In his follow-up book, The Peter Prescription, he offered possible solutions to the problems his principle could cause."
  "planck": "Planck's law - In physics, describes the spectral radiance of a black body at a given temperature. After Max Planck."
  "plateau": "Plateau's laws - Describe the structure of soap films. Named after Belgian physicist Joseph Plateau."
  "poe-poetry": "Poe's law (poetry) - There is a maximum desirable length for poems: \"The unit of poetry must be fixed by the reader's capacity of attention, and ... the limits of a poem must accord with the limits of a single movement of intellectual apprehension and emotional exaltation,\" named for Edgar Allan Poe.[3][4] See \"The Philosophy of Composition\"."
  "poe-religious": "Poe's law (religious fundamentalism) - \"Without a winking smiley or other blatant display of humour, it is impossible to create a parody of fundamentalism that someone won't mistake for the real thing.\"[5] named after Nathan Poe who formulated it on the Web site Christian Forums in 2005.[6] Although it originally referred to creationism, the scope later widened to religious fundamentalism.[7]"
  "poisson": "Poisson's law of large numbers - For independent random variables with a common distribution, the average value for a sample tends to the mean as sample size increases. Named after Siméon Denis Poisson (1781-1840) and derived from \"Recherches sur la probabilité des jugements en matière criminelle et en matière civile\" (1837; \"Research on the Probability of Criminal and Civil Verdicts\")."
  "postel": "Postel's law - Be conservative in what you do; be liberal in what you accept from others. Derived from RFC 761 (Transmission Control Protocol, 1980) in which Jon Postel summarized earlier communications of desired interoperability criteria for the Internet Protocol (cf. IEN 111)[8]"
  "powell": "Powell doctrine - In foreign policy, that specific questions are answered before initiating a military conflict (e.g. clear achievable objective, overwhelming force to minimize casualties, exit strategy)."
  "premack": "Premack's principle - More probable behaviors will reinforce less probable behaviors. Named by David Premack (1925 - )"
  "pythagorean": "Pythagorean theorem - is a relation in Euclidean geometry among the three sides of a right triangle (right-angled triangle). The Pythagorean theorem is named after the Greek mathematician Pythagoras"
  "raoult": "Raoult's law - In chemistry, Raoult's law states that the vapor pressure of mixed liquids is dependent on the vapor pressures of the individual liquids and the molar vulgar fraction of each present in solution."
  "reed": "Reed's law - The assertion of David P. Reed that the utility of large networks, particularly social networks, can scale exponentially with the size of the network."
  "reilly": "Reilly's law of retail gravitation - People generally patronize the largest mall in the area."
  "ribot": "Ribot's law - In amnesia, more recent memories are most affected."
  "ricco": "Ricco's law - In human vision, the product of contrast and area is a constant for small targets below the resolution limit."
  "roemer": "Roemer's law - A hospital bed built is a bed filled."
  "rothbard": "Rothbard's law - Everyone specializes in his own area of weakness."
  "sarnoff": "Sarnoff's law - The value of a broadcast network is proportional to the number of viewers."
  "say": "Say's law - Attributed to economist Jean-Baptiste Say by economist John Maynard Keynes, saying that \"supply creates its own demand\", i.e., if businesses produce more output in a free market economy, the wages and other payment for productive inputs will provide sufficient demand so that there is no general glut.[9]"
  "sayre": "Sayre's law - \"In any dispute the intensity of feeling is inversely proportional to the value of the stakes at issue.\" By way of corollary, the law adds: \"That is why academic politics are so bitter.\""
  "schneier": "Schneier's law - \"Any person can invent a security system so clever that she or he can't think of how to break it.\""
  "schottky-mott": "Schottky-Mott rule - Predicts the Schottky barrier height based on the vacuum work function of the metal relative to the vacuum electron affinity (or vacuum ionization energy) of the semiconductor. Named for Walter H. Schottky and Nevill Francis Mott."
  "segal": "Segal's law - \"A man with a watch knows what time it is. A man with two watches is never sure.\""
  "shermer": "Shermer's last law - A corollary of Clarke's three laws, it states that \"Any sufficiently advanced alien intelligence is indistinguishable from God.\" Originally posited in Michael Shermer's \"Skeptic\" column in the Jan 2002 issue of Scientific American."
  "shirky": "Shirky Principle - \"Institutions will try to preserve the problem to which they are the solution.\""
  "sievers": "Sievers' law - In Indo-European linguistics, accounts for the pronunciation of a consonant cluster with a glide (*w or *y) before a vowel as it was affected by the phonetics of the preceding syllable. Named after Germanic philologist Eduard Sievers (1859-1932)."
  "sieverts": "Sieverts' law - In physical metallurgy, a rule to predict the solubility of gases in metals. Named after German chemist Adolf Sieverts (1874-1947)."
  "simpson": "Simpson's paradox - In probability and statistics, Simpson's paradox, or the Yule-Simpson effect, is a paradox in which a trend that appears in different groups of data disappears when these groups are combined, and the reverse trend appears for the aggregate data."
  "smeed": "Smeed's law - An empirical rule relating traffic fatalities to traffic congestion as measured by the proxy of motor vehicle registrations and country population. After R. J. Smeed.[10]"
  "snell": "Snell's law - The simple formula used to calculate the refraction of light when travelling between two media of differing refractive index. It is named after one of its discoverers, Dutch mathematician Willebrord van Roijen Snell (1580-1626)."
  "snook": "Snook's law - As a verbal or written discussion about anything German progresses, the probability of a description related to 'efficiency' approaches 1."
  "sowa": "Sowa's law of standards - \"Whenever a major organization develops a new system as an official standard for X, the primary result is the widespread adoption of some simpler system as a de facto standard for X.\""
  "stang": "Stang's law - A Proto-Indo-European phonological rule named after Norwegian linguist Christian Stang. The law governs the word-final sequences of a vowel, followed by a laryngeal or a semivowel */y/ or */w/, followed by a nasal, and according to the law those sequences are simplified in a way that laryngeals and semivowels are dropped, with compensatory lengthening of a preceding vowel."
  "stark-einstein": "Stark-Einstein law - states that every photon that is absorbed will cause a (primary) chemical or physical reaction. Named after Johannes Stark and Albert Einstein."
  "stefan-boltzmann": "Stefan-Boltzmann law - The total energy radiated per unit surface area of a black body in unit time is directly proportional to the fourth power of the black body's thermodynamic temperature. Named for Jožef Stefan (1835-1893) and Ludwig Boltzmann."
  "stein": "Stein's law - If something cannot go on forever, it will stop. If a trend cannot go on forever, there is no need for action or a program to make it stop, much less to make it stop immediately; it will stop of its own accord."
  "stevens": "Stevens' power law - In psychophysics, this law relates the intensity of a stimulus to its perceived strength. It supersedes the Weber-Fechner law, since it can describe a wider range of sensations. The theory is named after its inventor, S. Smith Stevens (1906-1973)."
  "stigler": "Stigler's law - No scientific discovery is named after its original discoverer, named by statistician Stephen Stigler who attributes it to sociologist Robert K. Merton, making the law self-referential."
  "stokes": "Stokes' law - An expression for the frictional force exerted on spherical objects with very small Reynolds numbers, named for George Gabriel Stokes, (1819-1903)"
  "sturgeon": "Sturgeon's law - \"Ninety percent of everything is crud.\" Derived from a quote by science fiction author Theodore Sturgeon (1918-1985)."
  "sutton": "Sutton's law - \"Go where the money is\". Often cited in medical schools to teach new doctors to spend resources where they are most likely to pay off. The law is named after bank robber Willie Sutton, who when asked why he robbed banks, is claimed to have answered \"Because that's where the money is.\""
  "swanson": "Swanson's law - Similar to Moore's Law, Swanson's law is an observation that solar cell prices fall 20% for every doubling of solar cell industry manufacturing capacity. The law is named after SunPower Corporation founder Dr. Richard Swanson."
  "szemerényi": "Szemerényi's law - A Proto-Indo-European phonological rule, named after Hungarian linguist Oswald Szemerényi, according to which word-final clusters of vowels (V), resonants (R) and of either */s/ or */h₂/ are simplified by dropping the word-final fricative (*/h₂/ was phonetically itself probably a back fricative), with compensatory lengthening of the preceding vowel."
  "thomas": "Thomas theorem - \"If men define situations as real, they are real in their consequences,\" a social law as far as there are any. (After W.I. Thomas and D.S. Thomas.)"
  "titius-bode": "Titius-Bode law - \"a hypothesis that the bodies in some orbital systems, including the Sun's, orbit at semi-major axes in a function of planetary sequence\". Named for Johann Daniel Titius and Johann Elert Bode."
  "tobler": "Tobler's first law of geography - \"Everything is related to everything else, but near things are more related than distant things.\" Coined by Waldo R. Tobler (b. 1930)."
  "tully-fisher": "Tully-Fisher relation - Stated by R. Brent Tully and J. Richard Fisher, relates the intrinsic luminosity of a galaxy to its velocity width."
  "vegard": "Vegard's law - In metallurgy, an approximate empirical rule which holds that a linear relation exists, at constant temperature, between the crystal lattice parameter of an alloy and the concentrations of the constituent elements. Named for Lars Vegard."
  "verdoorn": "Verdoorn's law - In economics, this law pertains to the relationship between the growth of output and the growth of productivity. According to the law, faster growth in output increases productivity due to increasing returns. Named after Dutch economist, Petrus Johannes Verdoorn."
  "verner": "Verner's law - Stated by Karl Verner in 1875, Verner's law describes a historical sound change in the Proto-Germanic language whereby voiceless fricatives *f, *þ, *s and *x, when immediately following an unstressed syllable in the same word, underwent voicing and became respectively *b, *d, *z and *g."
  "wagner": "Wagner's law - Predicts that the development of an industrial economy will be accompanied by an increased share of public expenditure in gross national product, and is named after the German economist Adolph Wagner (1835-1917)."
  "weber-fechner": "Weber-Fechner law - This law named after the Germans Ernst Heinrich Weber and Gustav Theodor Fechner attempts to describe the human perception of various physical stimuli. In most cases, Stevens' power law gives a more accurate description."
  "werther": "Werther effect - A spike of emulation suicides after a widely publicized suicide, named after the protagonist of Goethe's novel The Sorrows of Young Werther."
  "weyl": "Weyl law - In Mathematics, describes the asymptotic behavior of eigenvalues of the Laplace-Beltrami operator. Named for Hermann Weyl."
  "wike": "Wike's law of low odd primes - \"If the number of experimental treatments is a low odd prime number, then the experimental design is unbalanced and partially confounded.\" (Wike, 1973, pp. 192-193).[11]"
  "wirth": "Wirth's law - Software gets slower faster than hardware gets faster."
  "wolff": "Wolff's law - Bone adapts to pressure, or a lack of it.[12]"
  "woodward-hoffmann": "Woodward-Hoffmann rules - in organic chemistry predicting the stereochemistry of pericyclic reactions based on orbital symmetry."
  "yao": "Yao's principle - In computational complexity theory, states that the expected cost of any randomized algorithm for solving a given problem, on the worst case input for that algorithm, can be no better than the expected cost, for a worst-case random probability distribution on the inputs, of the deterministic algorithm that performs best against that distribution. Named for Andrew Yao."
  "zawinski": "Zawinski's law - Every program attempts to expand until it can read mail. Those programs which cannot so expand are replaced by ones which can."
  "zeigarnik": "Zeigarnik effect - Named after Bluma Zeigarnik; people remember uncompleted or interrupted tasks better than completed tasks."
  "zipf": "Zipf's law - In linguistics, the observation that the frequency of use of the nth-most-frequently-used word in any natural language is approximately inversely proportional to n, or, more simply, that a few words are used very often, but many or most are used rarely. Named after George Kingsley Zipf (1902-1950), whose statistical body of research led to the observation. More generally, the term Zipf's law refers to the probability distributions involved, which are applied by statisticians not only to linguistics but also to fields remote from that."

module.exports = (robot) ->
  robot.respond /law (.*)/i, (msg) ->
    law = msg.match[1].toLowerCase() 
         
    if laws[law]
      # It found an exact match - return it
      msg.send "#{laws[law]}" 
    else 
      matches = []
      re = new RegExp(law,"g")
      
      # Loop through the indexes to see if there is a partial match
      for index, element of laws
        match = index.match(re)
        if match != null 
          matches.push index
               
      summary = "No such law, sucka. " 
      
      if matches.length > 0
        summary += "Perhaps you meant: "
        count = 1
        for element in matches         
          summary += "`#{element}`"
          if count != matches.length
            summary += ", "
          else 
            summary += "?"
          count++
      msg.send summary